import React, { useCallback, useEffect, useState } from 'react';
import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { Header } from 'src/components/Header';
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';

const useCounter = () => {
  const [count, setCount] = useState(1);
  const [isShow, setIsShow] = useState(true);

  const handleClick = useCallback(() => {
    if (count < 10) {
      setCount((count) => count + 1);
    }
  }, [count]);

  const handleDisplay = () => {
    setIsShow((isShow) => !isShow);
  };

  return { count, isShow, handleClick, handleDisplay };
};

export default function Home() {
  const { count, isShow, handleClick, handleDisplay } = useCounter();
  const [text, setText] = useState('');
  const [array, setArray] = useState([]);

  const handleChange = useCallback((e) => {
    if (e.target.value.length > 5) {
      alert('5文字以内にしてください');
      return;
    }
    setText(e.target.value.trim());
  }, []);

  const handleAdd = useCallback(() => {
    setArray((prevArray) => {
      if (prevArray.some((item) => item === text)) {
        alert('同じアイテムが存在します。');
        return prevArray;
      }
      return [...prevArray, text];
    });
  }, [text]);

  useEffect(() => {
    document.body.style.backgroundColor = 'lightblue';
    console.log('マウント時');
    return () => {
      document.body.style.backgroundColor = '';
      console.log('あんマウント時');
    };
  }, [count]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className={styles.count}>
        {isShow ? <h1>{count}</h1> : null}
        <button href='/about' onClick={handleClick}>
          ボタン
        </button>
        <button onClick={handleDisplay}>{isShow ? '非表示' : '表示'}</button>
        <input type='text' value={text} onChange={handleChange} />
        <button onClick={handleAdd}>追加</button>
        <ul>
          {array.map((item) => {
            return <li key={item}>{item}</li>;
          })}
        </ul>
      </div>
      <Main page='index' />
      <Footer />
    </div>
  );
}
