import React, { useCallback, useEffect, useState } from 'react';
import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { Header } from 'src/components/Header';
import { Footer } from 'src/components/Footer';
import { Main } from 'src/components/Main';

export default function Home() {
  const [count, setCount] = useState(1);
  const [text, setText] = useState('');
  const [isShow, setIsShow] = useState(true);
  const handleClick = useCallback(() => {
    if (count < 10) {
      setCount((count) => count + 1);
    }
  }, [count]);

  useEffect(() => {
    document.body.style.backgroundColor = 'lightblue';
    console.log('マウント時');
    return () => {
      document.body.style.backgroundColor = '';
      console.log('あんマウント時');
    };
  }, [count]);

  const handleChange = useCallback((e) => {
    if (e.target.value.length > 5) {
      alert('5文字以内にしてください');
      return;
    }
    setText(e.target.value.trim());
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className={styles.count}>
        {isShow ? <h1>{count}</h1> : null}
        <button href='/about' onClick={handleClick}>
          ボタン
        </button>
        <button
          onClick={() => {
            setIsShow((isShow) => {
              if (isShow === true) {
                return false;
              } else {
                return true;
              }
            });
          }}
        >
          非表示
        </button>
        <input type='text' value={text} onChange={handleChange} />
      </div>
      <Main page='index' />
      <Footer />
    </div>
  );
}
