import React from 'react';
import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { Header } from 'src/components/Header';
import { useRouter } from 'next/router';
import useSWR from 'swr';

const fetcher = async (url) => {
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error('エラーが発生したため、データの取得に失敗しました');
  }

  const json = await response.json();
  return json;
};

const PostId = () => {
  const router = useRouter();
  const { data, error } = useSWR('https://jsonplaceholder.typicode.com/posts/1', fetcher);

  return (
    <div className={styles.container}>
      <Head>
        <title>{data?.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <ol>
        <div>
          <h1>{data?.title}</h1>
          <p>{data?.body}</p>
        </div>
      </ol>
    </div>
  );
};

export default PostId;
