import React from 'react';
import Head from 'next/head';
import styles from 'src/styles/Home.module.css';
import { Header } from 'src/components/Header';
import { useRouter } from 'next/router';

const Home = () => {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <ol>
        <div>{router.query.id}</div>
      </ol>
    </div>
  );
};

export default Home;
